In [1]:
import numpy as np
arr = np.array([1,3,4,5,6])
arr

array([1, 3, 4, 5, 6])

In [2]:
arr.shape

(5,)

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr = np.array([1,'st','er',3])
arr.dtype

dtype('<U11')

In [6]:
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])#creating the array
arr.shape

(3, 3)

In [7]:
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [8]:
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr = np.random.randn(3,4)
arr

array([[-0.7840686 ,  0.4837003 ,  0.7798659 ,  0.09601748],
       [-0.28953419, -0.47653113, -0.39022201,  1.45314274],
       [ 0.63972685,  0.89833995,  1.08006675, -0.53762658]])

In [12]:
from io import BytesIO
b = BytesIO(b"2,23,33\n32,42,63.4\n35,77,12")
arr = np.genfromtxt(b, delimiter=",")
arr

array([[ 2. , 23. , 33. ],
       [32. , 42. , 63.4],
       [35. , 77. , 12. ]])

In [13]:
arr[1]

array([32. , 42. , 63.4])

In [14]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [15]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
arr = np.arange(10)
arr[5:]

array([5, 6, 7, 8, 9])

In [17]:
arr[5:8]

array([5, 6, 7])

In [18]:
arr[:-5]

array([0, 1, 2, 3, 4])

In [19]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [20]:
arr[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [21]:
arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [22]:
arr[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [23]:
arr[...,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [24]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
arr[[0,1,2],[1,0,0]]

array([1, 3, 6])

In [26]:
cities = np.array(["delhi","banglaore","mumbai","chennai","bhopal"])
city_data = np.random.randn(5,3)
city_data

array([[-1.1744508 , -0.23704807, -1.32230796],
       [ 2.01410031, -0.30243227,  0.3572452 ],
       [ 0.32001159, -0.86733841,  0.43191312],
       [ 0.12241317, -0.19334524,  1.25993142],
       [ 0.57924223, -0.05899682, -0.18325893]])

In [27]:
city_data[cities =="delhi"]

array([[-1.1744508 , -0.23704807, -1.32230796]])

In [28]:
city_data[city_data >0]

array([2.01410031, 0.3572452 , 0.32001159, 0.43191312, 0.12241317,
       1.25993142, 0.57924223])

In [29]:
city_data[city_data >0] = 0
city_data

array([[-1.1744508 , -0.23704807, -1.32230796],
       [ 0.        , -0.30243227,  0.        ],
       [ 0.        , -0.86733841,  0.        ],
       [ 0.        , -0.19334524,  0.        ],
       [ 0.        , -0.05899682, -0.18325893]])

In [30]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
arr + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [33]:
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(5).reshape(5,1)
arr2 + arr1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [34]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [35]:
arr2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [36]:
arr1 = np.random.randn(5,3)
arr1

array([[ 1.26167077, -1.17266963,  0.08883789],
       [-2.41301368, -0.53903079,  0.09274823],
       [ 1.16744537,  0.24522284, -0.55191132],
       [ 0.73325902, -1.27100439, -1.60043116],
       [-0.54679847, -0.95068911, -0.79092291]])

In [37]:
np.modf(arr1)

(array([[ 0.26167077, -0.17266963,  0.08883789],
        [-0.41301368, -0.53903079,  0.09274823],
        [ 0.16744537,  0.24522284, -0.55191132],
        [ 0.73325902, -0.27100439, -0.60043116],
        [-0.54679847, -0.95068911, -0.79092291]]), array([[ 1., -1.,  0.],
        [-2., -0.,  0.],
        [ 1.,  0., -0.],
        [ 0., -1., -1.],
        [-0., -0., -0.]]))

In [38]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[1,2,3]])
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

In [39]:
A = np.arange(15).reshape(3,5)
A.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [40]:
np.linalg.svd(A)

(array([[-0.15425367,  0.89974393,  0.40824829],
        [-0.50248417,  0.28432901, -0.81649658],
        [-0.85071468, -0.3310859 ,  0.40824829]]),
 array([3.17420265e+01, 2.72832424e+00, 3.59372947e-16]),
 array([[-0.34716018, -0.39465093, -0.44214167, -0.48963242, -0.53712316],
        [-0.69244481, -0.37980343, -0.06716206,  0.24547932,  0.55812069],
        [-0.41088392,  0.70864929,  0.02536563, -0.53314345,  0.21001245],
        [-0.40770221,  0.39487291, -0.09099898,  0.62818809, -0.5243598 ],
        [ 0.25485938,  0.20467429, -0.8894244 ,  0.14538841,  0.28450232]]))

In [41]:
a = np.array([[7,5,-3], [3,-5,2],[5,3,-7]])
b = np.array([16,-8,0])
x = np.linalg.solve(a, b)
x

array([1., 3., 2.])

In [44]:
np.allclose(np.dot(a, x),b)

True

In [45]:
import pandas as pd
d =  [{'city':'Delhi',"data":1000},
      {'city':'Banglaore',"data":2000},
      {'city':'Mumbai',"data":1000}]
pd.DataFrame(d)

city  data
0      Delhi  1000
1  Banglaore  2000
2     Mumbai  1000

In [46]:
df = pd.DataFrame(d)

In [47]:
city_data = pd.read_csv(filepath_or_buffer='simplemaps-worldcities-basic.csv')

In [48]:
city_data.head(n=10)

city      city_ascii        lat        lng       pop  \
0   Qal eh-ye Now       Qal eh-ye  34.983000  63.133300    2997.0   
1     Chaghcharan     Chaghcharan  34.516701  65.250001   15000.0   
2     Lashkar Gah     Lashkar Gah  31.582998  64.360000  201546.0   
3          Zaranj          Zaranj  31.112001  61.886998   49851.0   
4      Tarin Kowt      Tarin Kowt  32.633298  65.866699   10000.0   
5    Zareh Sharan    Zareh Sharan  32.850000  68.416705   13737.0   
6        Asadabad        Asadabad  34.866000  71.150005   48400.0   
7         Taloqan         Taloqan  36.729999  69.540004   64256.0   
8  Mahmud-E Eraqi  Mahmud-E Eraqi  35.016696  69.333301    7407.0   
9      Mehtar Lam      Mehtar Lam  34.650000  70.166701   17345.0   

       country iso2 iso3 province  
0  Afghanistan   AF  AFG  Badghis  
1  Afghanistan   AF  AFG     Ghor  
2  Afghanistan   AF  AFG  Hilmand  
3  Afghanistan   AF  AFG   Nimroz  
4  Afghanistan   AF  AFG  Uruzgan  
5  Afghanistan   AF  AFG  Paktika  
6  Afghanistan   AF  AFG    Kunar  
7  Afghanistan   AF  AFG   Takhar  
8  Afghanistan   AF  AFG   Kapisa  
9  Afghanistan   AF  AFG  Laghman

In [49]:
city_data.tail()

city   city_ascii        lat        lng        pop   country  \
7317       Mutare       Mutare -18.970019  32.650038   216785.0  Zimbabwe   
7318       Kadoma       Kadoma -18.330006  29.909947    56400.0  Zimbabwe   
7319  Chitungwiza  Chitungwiza -18.000001  31.100003   331071.0  Zimbabwe   
7320       Harare       Harare -17.817790  31.044709  1557406.5  Zimbabwe   
7321     Bulawayo     Bulawayo -20.169998  28.580002   697096.0  Zimbabwe   

     iso2 iso3          province  
7317   ZW  ZWE        Manicaland  
7318   ZW  ZWE  Mashonaland West  
7319   ZW  ZWE            Harare  
7320   ZW  ZWE            Harare  
7321   ZW  ZWE          Bulawayo

In [50]:
series_es = city_data.lat

In [51]:
type(series_es)

pandas.core.series.Series

In [52]:
series_es[1:10:2]

1    34.516701
3    31.112001
5    32.850000
7    36.729999
9    34.650000
Name: lat, dtype: float64

In [53]:
series_es[:7]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [54]:
series_es[:-7315]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [55]:
city_data[:7]

city    city_ascii        lat        lng       pop      country  \
0  Qal eh-ye Now     Qal eh-ye  34.983000  63.133300    2997.0  Afghanistan   
1    Chaghcharan   Chaghcharan  34.516701  65.250001   15000.0  Afghanistan   
2    Lashkar Gah   Lashkar Gah  31.582998  64.360000  201546.0  Afghanistan   
3         Zaranj        Zaranj  31.112001  61.886998   49851.0  Afghanistan   
4     Tarin Kowt    Tarin Kowt  32.633298  65.866699   10000.0  Afghanistan   
5   Zareh Sharan  Zareh Sharan  32.850000  68.416705   13737.0  Afghanistan   
6       Asadabad      Asadabad  34.866000  71.150005   48400.0  Afghanistan   

  iso2 iso3 province  
0   AF  AFG  Badghis  
1   AF  AFG     Ghor  
2   AF  AFG  Hilmand  
3   AF  AFG   Nimroz  
4   AF  AFG  Uruzgan  
5   AF  AFG  Paktika  
6   AF  AFG    Kunar

In [56]:
city_data.iloc[:5,:4]

city   city_ascii        lat        lng
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300
1    Chaghcharan  Chaghcharan  34.516701  65.250001
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000
3         Zaranj       Zaranj  31.112001  61.886998
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699

In [57]:
city_data[city_data['pop'] > 10000000][city_data.columns[pd.Series(city_data.columns).str.startswith('l')]]

lat         lng
360  -34.602502  -58.397531
1171 -23.558680  -46.625020
2068  31.216452  121.436505
3098  28.669993   77.230004
3110  19.016990   72.856989
3492  35.685017  139.751407
4074  19.442442  -99.130988
4513  24.869992   66.990009
5394  55.752164   37.615523
6124  41.104996   29.010002
7071  40.749979  -73.980017

In [58]:
city_greater_10mil = city_data[city_data['pop'] > 10000000]
city_greater_10mil.rename(columns={'pop':'population'}, inplace=True)
city_greater_10mil.where(city_greater_10mil.population > 15000000)

C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)


city city_ascii        lat         lng  population country iso2 iso3  \
360      NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
1171     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
2068     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
3098     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
3110  Mumbai     Mumbai  19.016990   72.856989  15834918.0   India   IN  IND   
3492   Tokyo      Tokyo  35.685017  139.751407  22006299.5   Japan   JP  JPN   
4074     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
4513     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
5394     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
6124     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
7071     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   

         province  
360           NaN  
1171          NaN  
2068          NaN  
3098          NaN  
3110  Maharashtra  
3492        Tokyo  
4074          NaN  
4513          NaN  
5394          NaN  
6124          NaN  
7071          NaN

In [59]:
df = pd.DataFrame(np.random.randn(8, 3),
columns=['A', 'B', 'C'])

In [60]:
nparray = df.values
type(nparray)

numpy.ndarray

In [61]:
from numpy import nan
df.iloc[4,2] = nan

In [62]:
df

A         B         C
0  0.340465 -2.840526  1.582031
1 -0.145989  1.107407  1.135358
2  0.379407 -0.172031 -0.748536
3  0.684805  0.443879 -1.055024
4 -0.244824  0.166547       NaN
5 -1.407995  1.497578 -0.230906
6  0.898935  0.908754  0.057770
7 -0.307762  0.479550  0.358739

In [63]:
df.fillna(0)

A         B         C
0  0.340465 -2.840526  1.582031
1 -0.145989  1.107407  1.135358
2  0.379407 -0.172031 -0.748536
3  0.684805  0.443879 -1.055024
4 -0.244824  0.166547  0.000000
5 -1.407995  1.497578 -0.230906
6  0.898935  0.908754  0.057770
7 -0.307762  0.479550  0.358739

In [64]:
columns_numeric = ['lat','lng','pop']

In [65]:
city_data[columns_numeric].mean()

lat        20.662876
lng        10.711914
pop    265463.071633
dtype: float64

In [66]:
city_data[columns_numeric].sum()

lat    1.512936e+05
lng    7.843263e+04
pop    1.943721e+09
dtype: float64

In [67]:
city_data[columns_numeric].count()

lat    7322
lng    7322
pop    7322
dtype: int64

In [68]:
city_data[columns_numeric].median()

lat       26.792730
lng       18.617509
pop    61322.750000
dtype: float64

In [69]:
city_data[columns_numeric].quantile(0.8)

lat        46.852480
lng        89.900018
pop    269210.000000
Name: 0.8, dtype: float64

In [70]:
city_data[columns_numeric].sum(axis = 1).head()

0      3095.116300
1     15099.766702
2    201641.942998
3     49943.998999
4     10098.499997
dtype: float64

In [71]:
city_data[columns_numeric].describe()

lat          lng           pop
count  7322.000000  7322.000000  7.322000e+03
mean     20.662876    10.711914  2.654631e+05
std      29.134818    79.044615  8.287622e+05
min     -89.982894  -179.589979 -9.900000e+01
25%      -0.324710   -64.788472  1.734425e+04
50%      26.792730    18.617509  6.132275e+04
75%      43.575448    73.103628  2.001726e+05
max      82.483323   179.383304  2.200630e+07

In [72]:
city_data1 = city_data.sample(3)

In [73]:
city_data2 = city_data.sample(3)
city_data_combine = pd.concat([city_data1,city_data2])
city_data_combine

city  city_ascii        lat         lng        pop  \
3870       Bogue       Bogue  16.590394  -14.269966    10415.0   
3486      Sendai      Sendai  38.287106  141.021717  1643781.0   
5265   De Kastri   De Kastri  51.466586  140.783334     3615.0   
3548        Shar        Shar  49.600317   81.054939     5124.5   
3503  Mangyshlak  Mangyshlak  43.690455   51.141736   147443.0   
2188       Demba       Demba  -5.509600   22.259974    17008.5   

               country iso2 iso3          province  
3870        Mauritania   MR  MRT            Brakna  
3486             Japan   JP  JPN            Miyagi  
5265            Russia   RU  RUS        Khabarovsk  
3548        Kazakhstan   KZ  KAZ   East Kazakhstan  
3503        Kazakhstan   KZ  KAZ       Mangghystau  
2188  Congo (Kinshasa)   CD  COD  Kasaï-Occidental

In [74]:
df1 = pd.DataFrame({'col1': ['col10', 'col11', 'col12', 'col13'],
                    'col2': ['col20', 'col21', 'col22', 'col23'],
                    'col3': ['col30', 'col31', 'col32', 'col33'],
                    'col4': ['col40', 'col41', 'col42', 'col43']},
                   index=[0, 1, 2, 3])

In [75]:
df1

col1   col2   col3   col4
0  col10  col20  col30  col40
1  col11  col21  col31  col41
2  col12  col22  col32  col42
3  col13  col23  col33  col43

In [76]:
df4 = pd.DataFrame({'col2': ['col22', 'col23', 'col26', 'col27'],
                    'Col4': ['Col42', 'Col43', 'Col46', 'Col47'],
                    'col6': ['col62', 'col63', 'col66', 'col67']},
                   index=[2, 3, 6, 7])

pd.concat([df1,df4], axis=1)

col1   col2   col3   col4   col2   Col4   col6
0  col10  col20  col30  col40    NaN    NaN    NaN
1  col11  col21  col31  col41    NaN    NaN    NaN
2  col12  col22  col32  col42  col22  Col42  col62
3  col13  col23  col33  col43  col23  Col43  col63
6    NaN    NaN    NaN    NaN  col26  Col46  col66
7    NaN    NaN    NaN    NaN  col27  Col47  col67

In [77]:
country_data = city_data[['iso3','country']].drop_duplicates()

In [78]:
country_data.shape

(223, 2)

In [79]:
country_data.head()

iso3         country
0    AFG     Afghanistan
33   ALD           Aland
34   ALB         Albania
60   DZA         Algeria
111  ASM  American Samoa

In [80]:
del(city_data['country'])

In [81]:
city_data.merge(country_data, 'inner').head()

city   city_ascii        lat        lng       pop iso2 iso3  \
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300    2997.0   AF  AFG   
1    Chaghcharan  Chaghcharan  34.516701  65.250001   15000.0   AF  AFG   
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000  201546.0   AF  AFG   
3         Zaranj       Zaranj  31.112001  61.886998   49851.0   AF  AFG   
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699   10000.0   AF  AFG   

  province      country  
0  Badghis  Afghanistan  
1     Ghor  Afghanistan  
2  Hilmand  Afghanistan  
3   Nimroz  Afghanistan  
4  Uruzgan  Afghanistan

In [82]:
from sklearn import datasets
diabetes = datasets.load_diabetes()
X = diabetes.data[:10]
y = diabetes.target

In [83]:
X[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087]])

In [84]:
y[:10]

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310.])

In [85]:
feature_names=['age', 'sex', 'bmi', 'bp',
               's1', 's2', 's3', 's4', 's5', 's6']

In [86]:
from sklearn import datasets
from sklearn.linear_model import Lasso

from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

diabetes = datasets.load_diabetes()
X_train = diabetes.data[:310]
y_train = diabetes.target[:310]

X_test = diabetes.data[310:]
y_test = diabetes.target[310:]

lasso = Lasso(random_state=0)
alphas = np.logspace(-4, -0.5, 30)

scores = list()
scores_std = list()

estimator = GridSearchCV(lasso,
                         param_grid = dict(alpha=alphas))

estimator.fit(X_train, y_train)

C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=0,
   selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'alpha': array([1.00000e-04, 1.32035e-04, 1.74333e-04, 2.30181e-04, 3.03920e-04,
       4.01281e-04, 5.29832e-04, 6.99564e-04, 9.23671e-04, 1.21957e-03,
       1.61026e-03, 2.12611e-03, 2.80722e-03, 3.70651e-03, 4.89390e-03,
       6.46167e-03, 8.53168e-03, 1.12648e-02, 1.48735e-02, 1.96383e-02,
       2.59294e-02, 3.42360e-02, 4.52035e-02, 5.96846e-02, 7.88046e-02,
       1.04050e-01, 1.37382e-01, 1.81393e-01, 2.39503e-01, 3.16228e-01])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [87]:
estimator.best_score_

0.4654063759023531

In [88]:
estimator.best_estimator_

Lasso(alpha=0.02592943797404667, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=False, positive=False, precompute=False,
   random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [89]:
estimator.predict(X_test)

array([203.42104984, 177.6595529 , 122.62188598, 212.81136958,
       173.61633075, 114.76145025, 202.36033584, 171.70767813,
       164.28694562, 191.29091477, 191.41279009, 288.2772433 ,
       296.47009002, 234.53378413, 210.61427168, 228.62812055,
       156.74489991, 225.08834492, 191.75874632, 102.81600989,
       172.373221  , 111.20843429, 290.22242876, 178.64605207,
        78.13722832,  86.35832297, 256.41378529, 165.99622543,
       121.29260976, 153.48718848, 163.09835143, 180.0932902 ,
       161.4330553 , 155.80211635, 143.70181085, 126.13753819,
       181.06471818, 105.03679977, 131.0479936 ,  90.50606427,
       252.66486639,  84.84786067,  59.41005358, 184.51368208,
       201.46598714, 129.96333913,  90.65641478, 200.10932516,
        55.2884802 , 171.60459062, 195.40750666, 122.14139787,
       231.72783897, 159.49750022, 160.32104862, 165.53701866,
       260.73217736, 259.77213787, 204.69526082, 185.66480969,
        61.09821961, 209.9214333 , 108.50410841, 141.18

In [98]:
import numpy
import theano.tensor as T
from theano import function
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y

In [99]:
f = function([x, y], z)
f(8, 2)

array(10.)

In [101]:
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

b'Hello, TensorFlow!'


In [103]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

X_train = cancer.data[:340]
y_train = cancer.target[:340]

X_test = cancer.data[340:]
y_test = cancer.target[340:]

import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout

Using TensorFlow backend.


In [104]:
model = Sequential()
model.add(Dense(15, input_dim=30, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

W0822 21:42:56.319474 13852 deprecation_wrapper.py:119] From C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0822 21:42:56.325418 13852 deprecation_wrapper.py:119] From C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0822 21:42:56.558404 13852 deprecation_wrapper.py:119] From C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [105]:
model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

W0822 21:43:13.811420 13852 deprecation_wrapper.py:119] From C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0822 21:43:13.923907 13852 deprecation_wrapper.py:119] From C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0822 21:43:13.972910 13852 deprecation.py:323] From C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [106]:
model.fit(X_train, y_train,
          epochs=20,
          batch_size=50)

W0822 21:43:32.389540 13852 deprecation_wrapper.py:119] From C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/20
340/340 [==============================] - 3s 10ms/step - loss: 8.6753 - acc: 0.4618
Epoch 2/20
340/340 [==============================] - 0s 70us/step - loss: 8.6753 - acc: 0.4618
Epoch 3/20
340/340 [==============================] - 0s 61us/step - loss: 8.6753 - acc: 0.4618
Epoch 4/20
340/340 [==============================] - 0s 68us/step - loss: 8.6753 - acc: 0.4618
Epoch 5/20
340/340 [==============================] - 0s 62us/step - loss: 8.6753 - acc: 0.4618
Epoch 6/20
340/340 [==============================] - 0s 57us/step - loss: 8.6753 - acc: 0.4618
Epoch 7/20
340/340 [==============================] - 0s 69us/step - loss: 8.6753 - acc: 0.4618
Epoch 8/20
340/340 [==============================] - 0s 62us/step - loss: 8.6753 - acc: 0.4618
Epoch 9/20
340/340 [==============================] - 0s 47us/step - loss: 8.6753 - acc: 0.4618
Epoch 10/20
340/340 [==============================] - 0s 41us/step - loss: 8.6753 - acc: 0.4618
Epoch 11/20
340/340 [==================

In [107]:
predictions = model.predict_classes(X_test)

In [108]:
from sklearn import metrics

print('Accuracy:', metrics.accuracy_score(y_true=y_test, y_pred=predictions))
print(metrics.classification_report(y_true=y_test, y_pred=predictions))

Accuracy: 0.24017467248908297
              precision    recall  f1-score   support

           0       0.24      1.00      0.39        55
           1       0.00      0.00      0.00       174

   micro avg       0.24      0.24      0.24       229
   macro avg       0.12      0.50      0.19       229
weighted avg       0.06      0.24      0.09       229



C:\Users\SAPTADEEPA RAY\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [109]:
model = Sequential()
model.add(Dense(15, input_dim=30, activation='relu'))
model.add(Dense(15, activation='relu'))
model.add(Dense(15, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(X_train, y_train,
          epochs=20,
          batch_size=50)

Epoch 1/20
340/340 [==============================] - 1s 2ms/step - loss: 1.3728 - acc: 0.6588
Epoch 2/20
340/340 [==============================] - 0s 62us/step - loss: 0.3512 - acc: 0.8706
Epoch 3/20
340/340 [==============================] - 0s 60us/step - loss: 0.3409 - acc: 0.8559
Epoch 4/20
340/340 [==============================] - 0s 74us/step - loss: 0.2579 - acc: 0.9088
Epoch 5/20
340/340 [==============================] - 0s 52us/step - loss: 0.5659 - acc: 0.8118
Epoch 6/20
340/340 [==============================] - 0s 70us/step - loss: 0.2755 - acc: 0.9029
Epoch 7/20
340/340 [==============================] - 0s 65us/step - loss: 0.3273 - acc: 0.8618
Epoch 8/20
340/340 [==============================] - 0s 66us/step - loss: 0.3508 - acc: 0.8765
Epoch 9/20
340/340 [==============================] - 0s 64us/step - loss: 0.2690 - acc: 0.9029
Epoch 10/20
340/340 [==============================] - 0s 90us/step - loss: 0.3091 - acc: 0.8735
Epoch 11/20
340/340 [===================

In [110]:
predictions = model.predict_classes(X_test)

In [111]:
print('Accuracy:', metrics.accuracy_score(y_true=y_test, y_pred=predictions))
print(metrics.classification_report(y_true=y_test, y_pred=predictions))

Accuracy: 0.9039301310043668
              precision    recall  f1-score   support

           0       0.84      0.75      0.79        55
           1       0.92      0.95      0.94       174

   micro avg       0.90      0.90      0.90       229
   macro avg       0.88      0.85      0.86       229
weighted avg       0.90      0.90      0.90       229

